export const FETCH_PROBLEMS = 'FETCH_PROBLEMS';
export const FETCH_PROBLEMS_START = 'FETCH_PROBLEMS_START';
export const FETCH_PROBLEMS_FINISH = 'FETCH_PROBLEMS_FINISH';
export const FETCH_PROBLEMS_ERROR = 'FETCH_PROBLEMS_ERROR';

export const REFETCH_PROBLEMS = 'REFETCH_PROBLEMS';

export const FETCH_ALL_PROBLEMS = 'FETCH_ALL_PROBLEMS';
export const FETCH_ALL_PROBLEMS_START = 'FETCH_ALL_PROBLEMS_START';
export const FETCH_ALL_PROBLEMS_FINISH = 'FETCH_ALL_PROBLEMS_FINISH';
export const FETCH_ALL_PROBLEMS_ERROR = 'FETCH_ALL_PROBLEMS_ERROR';

export const REFETCH_ALL_PROBLEMS = 'REFETCH_ALL_PROBLEMS';

export const SELECT_PROBLEM = 'SELECT_PROBLEM';

export const SAW_RESPONSES_OF_PROBLEM = 'SAW_RESPONSES_OF_PROBLEM';

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START';
export const FETCH_USER_INFO_FINISH = 'FETCH_USER_INFO_FINISH';
export const FETCH_USER_INFO_ERROR = 'FETCH_USER_INFO_ERROR';
